const fs = require('fs');
const crypto = require('crypto');

const data = JSON.parse(fs.readFileSync('dump.json', 'utf-8'));

function uuid() {
    return crypto.randomUUID();
}

const userMap = {}; // old_id -> new_uuid

let sql = `-- Full Restore Script

-- 1. Create Tables
CREATE TABLE IF NOT EXISTS public.projects (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id UUID REFERENCES auth.users(id) ON DELETE CASCADE NOT NULL,
    name TEXT NOT NULL,
    folder_path TEXT,
    last_file TEXT,
    created_at TIMESTAMPTZ DEFAULT now()
);

CREATE TABLE IF NOT EXISTS public.project_versions (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    project_id BIGINT REFERENCES public.projects(id) ON DELETE CASCADE NOT NULL,
    version TEXT NOT NULL,
    label TEXT,
    files TEXT NOT NULL, -- JSON string
    created_at TIMESTAMPTZ DEFAULT now()
);

-- Enable RLS
ALTER TABLE public.projects ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.project_versions ENABLE ROW LEVEL SECURITY;

-- Create Policies safely using DO blocks
DO $$ 
BEGIN
    IF NOT EXISTS (SELECT 1 FROM pg_policies WHERE policyname = 'Users can do anything with their own projects') THEN
        CREATE POLICY "Users can do anything with their own projects" ON public.projects FOR ALL USING (auth.uid() = user_id);
    END IF;
END $$;

DO $$ 
BEGIN
    IF NOT EXISTS (SELECT 1 FROM pg_policies WHERE policyname = 'Users can do anything with their own versions') THEN
        CREATE POLICY "Users can do anything with their own versions" ON public.project_versions FOR ALL USING (
            EXISTS (SELECT 1 FROM public.projects WHERE projects.id = project_versions.project_id AND projects.user_id = auth.uid())
        );
    END IF;
END $$;

\n-- 2. Insert Users + Identities\n`;

for (const u of data.users) {
    const newId = uuid();
    userMap[u.id] = newId;
    const email = `${u.username}@roode.app`;
    const pass = u.password.replace(/'/g, "''");
    const identityId = uuid();

    sql += `DO $wrap$ BEGIN
  INSERT INTO auth.users (id, instance_id, aud, role, email, encrypted_password, email_confirmed_at, raw_app_meta_data, raw_user_meta_data, created_at, updated_at)
  VALUES (
    '${newId}',
    '00000000-0000-0000-0000-000000000000',
    'authenticated',
    'authenticated',
    '${email}',
    '${pass}',
    now(),
    '{"provider":"email","providers":["email"]}',
    '{"username":"${u.username}"}',
    '${u.created_at}',
    '${u.created_at}'
  );
  INSERT INTO auth.identities (id, provider_id, user_id, identity_data, provider, last_sign_in_at, created_at, updated_at)
  OVERRIDING SYSTEM VALUE
  VALUES (
    '${identityId}',
    '${newId}',
    '${newId}',
    '{"sub":"${newId}","email":"${email}"}',
    'email',
    now(),
    '${u.created_at}',
    '${u.created_at}'
  );
EXCEPTION WHEN unique_violation THEN NULL;
END $wrap$;\n`;
}

sql += `\n-- 3. Insert Projects\n`;
for (const p of data.projects) {
    const newUserId = userMap[p.user_id];
    if (!newUserId) continue;

    const name = p.name.replace(/'/g, "''");
    const folder = p.folder_path.replace(/'/g, "''");
    const lastFile = p.last_file ? p.last_file.replace(/'/g, "''") : 'NULL';
    const lastFileStr = lastFile === 'NULL' ? lastFile : `'${lastFile}'`;

    sql += `DO $wrap$ BEGIN
  INSERT INTO public.projects (id, user_id, name, folder_path, last_file, created_at)
  OVERRIDING SYSTEM VALUE
  VALUES (
    ${p.id},
    '${newUserId}',
    '${name}',
    '${folder}',
    ${lastFileStr},
    '${p.created_at}'
  );
EXCEPTION WHEN unique_violation OR foreign_key_violation THEN NULL;
END $wrap$;\n`;
}

sql += `\n-- 4. Insert Versions\n`;
for (const v of data.versions) {
    const label = v.label ? v.label.replace(/'/g, "''") : 'NULL';
    const labelStr = label === 'NULL' ? label : `'${label}'`;
    const files = v.files.replace(/'/g, "''");

    sql += `DO $wrap$ BEGIN
  INSERT INTO public.project_versions (id, project_id, version, label, files, created_at)
  OVERRIDING SYSTEM VALUE
  VALUES (
    ${v.id},
    ${v.project_id},
    '${v.version}',
    ${labelStr},
    '${files}',
    '${v.created_at}'
  );
EXCEPTION WHEN unique_violation OR foreign_key_violation THEN NULL;
END $wrap$;\n`;
}

sql += `\n-- 5. Reset Sequences\n`;
sql += `SELECT setval('public.projects_id_seq', (SELECT MAX(id) FROM public.projects));\n`;
sql += `SELECT setval('public.project_versions_id_seq', (SELECT MAX(id) FROM public.project_versions));\n`;

fs.writeFileSync('migration.sql', sql);
console.log('Done! Now run migration.sql in Supabase SQL Editor.');
